The world is on fire, but don’t you worry, I’m here to tell you how to clean your smartphone.
That is, if you really want to clean your phone. Three people I spoke with over the past week said they did not clean their smartphones—and they’re all leading experts on microbiology and infectious disease.
WAIT! WHAT? I thought smartphones were dirtier than a toilet bowl. Heck, even academic studies, like this one from my favorite bedtime reading, the Journal of Hospital Infection, have found considerable amounts of bacteria, including fecal matter, on phone screens.A recent study found that, on surfaces such as metal, glass or plastic, coronavirus can survive for anywhere between two hours and nine days.
“My phone is the least of my concerns,” says Alex Berezow, a microbiologist and vice president at the American Council on Science and Health. “Worry about touching door handles that thousands of other people touch.”
After days of disinfecting my phone like a surgical tray, I was shocked. Phone cleaning is certainly not as cut and dried as you thought. After hours of research and scrubbing phones with everything from Clorox wipes to Lysol toilet-bowl cleaner, I’ve come up with some basic lessons for what you can do—and not do—with that petri dish phone of yours.
		Should I clean my smartphone?
Let’s be very clear: Even when there isn’t a pandemic sweeping the globe, your phone can get dirty.
Generally, that filth is not an issue, says Emma Hayhurst, a microbiologist at the University of South Wales and co-author on the aforementioned Journal of Hospital Infection paper. “We were trying to avoid mass panic about mucky phones. When you are healthy, it’s really not a problem.”
Translation: You should clean your phone—just not compulsively.
“We don’t need to be obsessively washing our phones right now. If people are coming into contact with coronavirus patients, then, yes. Wash your phone all the time. Not because there is evidence that it will transmit via a phone but because there is no evidence that it won’t,” says Dr. Hayhurst.
		How should I clean my smartphone?
It’s long been the guidance of Apple, Samsung and other phone makers to just use a microfiber cloth to shine up your device.
All my new infectious-disease friends, however, say that to effectively kill the virus on a surface, you need disinfectant solution—for instance, something with at least 55% isopropyl alcohol.
On Monday, I reported that Apple updated its website to remove its blanket ban on all cleaning supplies. It now gives the OK to use a 70% isopropyl alcohol wipe or Clorox disinfecting wipe on the surface of all Apple products. Google also confirmed that it’s OK to use isopropyl alcohol or Clorox wipes to clean its Pixel devices.
After publication of this column, Samsung updated its cleaning guidance to include alcohol-based cleaners. It now advises Galaxy owners to dampen a cloth with a disinfectant or alcohol-based solution and wipe gently. It says not to apply liquid directly onto your phone.
		Can I damage my smartphone by cleaning it?
The big cleaning-solution fear cited by smartphone makers is damage to your phone screen’s oleophobic layer. This is a protective coating on your screen that repels both water and oil. Basically, it helps minimize fingerprints and smudges.
“Cleaning products and abrasive materials will diminish the coating and might scratch your iPhone,” Apple’s website reads.
I took it upon myself to test that, Using a brand-new iPhone 8, I wiped the screen 1,095 times with Clorox disinfecting wipes. I figured that’s the equivalent of wiping down your phone every day for the three years you might own it. The only thing showing any wear after all that wiping? My poor, wrinkly fingers. The coating still repelled drops of olive oil like it did when I first took it out of the box.
So I upped the effort. I was told that hydrochloric acid, found in toilet-bowl cleaner, would take it right off. Yet after five minutes of scrubbing, it was still fine. Soft Scrub with some bleach for five minutes? Still in decent shape. Finally, I decided to let it sit in a stew of toilet-bowl cleaner for two hours, then I threw in a five-minute rubdown with nail-polish remover, which has acetone. That did it…just about. (The phone, miraculously, still worked.)
Should you do any of that? Absolutely not, but these screens are far more resistant to these products than I’d thought. Plus, the oleophobic layer on your phone is going to wear from normal use anyway.
When cleaning with your disinfecting wipes, however, avoid getting liquid in the ports. Even if most phones are now water resistant, that resistance wears over time.
Our anxieties are at an all-time high, understandably. If cleaning makes you feel better, grab some wipes and go to town. Wipe for hours—even days. Your phone will be just fine. Just remember, you really don’t need to. Unless you’re one of those crazy phone lickers.
— Kenny Wassus contributed to this column.