There have been several articles suggesting a vaccine against the new coronavirus will be available to prevent COVID-19 soon. For example, Chinese officials have claimed that they will have a vaccine ready next month to be used for this pandemic. A vaccine manufacturer  claims to have shipped vials of an mRNA vaccine against the virus for the first phase 1 testing.
Though this is promising news some caution is required as the vaccine manufacturing process and safety testing is typically very thorough. There are several safety criteria need to be met before a vaccine is approved for widespread use. Some vaccines can take more than 5 years to be proven safe, effective and for production processes to be consistent enough for them to enter the market.
There are reports of several vaccines in development and mRNA vaccines are one promising type. Best estimates are that with fast-track processes for approval it will be 12-18 months before a licensed vaccine for coronavirus could be ready for wide use.

		Where did the story come from?
In Beijing, the director of the National Health Commission’s Science and Technology Development Centre claimed in the South China Morning Post that a coronavirus vaccine will be ready next month. He said it is to be used for emergency situations and clinical trials, and eight institutes in China are working on different approaches to fight COVID-19. Sometime in April they hope to have the vaccine available.
Moderna Therapeutics, a US biotechnology company, has developed a synthetic messenger RNA (mRNA) vaccine that they say was “handed” to the heads of the US government for testing.

		What is the basis for the claim?
This global pandemic has affected more than 130,000 people and killed almost 5000 worldwide according to WHO data (12th March). The genetic code for the virus was sent out by email to many research institutes very quickly after the viral genome was characterised. The WHO is supporting efforts to develop a vaccine.
The two claims that a vaccine will be ready in a few weeks caused excitement at a press conference in the White House on March 2. Anthony Fauci, the respected head of the National Institutes of Allergy and Infectious Disease, clarified his view of the claim saying “You wouldn’t have a vaccine. You would have a vaccine to go into testing.”
These mRNA vaccines have been previously tested for Zika and were produced by Regeneron Pharmaceuticals, CureVac, and Inovio Pharmaceuticals, amongst others. They have received an FDA Fast track designation, meaning there is a precedent for prioritising approval if safe and effective. However, the reality is that these new technologies and vaccines have yet to be shown to work.
This is an exciting and fast-moving field of research with promising progress being made. For example, in 2018 a DNA vaccine has reportedly been licensed in China to prevent H5 subtype avian influenza infection in chickens.

		What do trusted sources say?
A recent overview from the University of Pennsylvania looked at the complexity and costs of vaccine manufacturing and it suggests that the regulatory requirements can be challenging for the vaccine manufacture industry. The steps that are necessary to produce a vaccine that is ‘safe, effective and consistent’ are difficult to execute over the life cycle of a vaccine.
This overview also found that most manufacturers typically have a vaccine portfolio which mitigates the high fixed costs of manufacturing in global markets but the production challenges for global vaccines can extend the time to reach required scale. An estimate of the time required, production and research phases, for bringing a product to the international market ranges was estimated at between five and eighteen years.
The Centers for Disease Control and Prevention state that the best way to prevent COVID-19 illness is to avoid being exposed to the virus. It seems that fast track processes may allow a new coronavirus vaccine to be tested in large trials by early next year.