Some countries have been using screening measures at borders, such as taking travellers’ temperatures, to try and stop people with the novel coronavirus entering. Can this approach work?
Unfortunately these measures alone are not able to completely stop the virus. A recent study suggested that almost half (46%) of novel coronavirus cases would be missed by temperature screening alone. This is because some travellers may be infected but not yet showing symptoms such as fever.
Research looking at entry screening in previous outbreaks of diseases such as SARS and pandemic flu also suggests that it identified either very few or no cases. However, it may provide an opportunity to educate travellers about the disease and what to do if they develop symptoms.
In the early stages of the outbreak the WHO advised screening of passengers leaving areas with ongoing community transmission of the virus, such as in China, where the virus was most common. The UK government currently requires flights and ships from high risk countries to provide a declaration stating that all their passengers are well before landing or docking.

		Where did the story come from?
Some countries have restricted entry from the countries which are badly affected by COVID-19. Other countries have started using screening measures on entry such as temperature screening for passengers arriving from high risk countries. In Wuhan, where the outbreak began, airport temperature screening was also used in the early stages to stop infected passengers leaving the area.

		What is the basis for the claim?
When a new infectious disease arises, stopping infected people from travelling and spreading it further makes sense, but often few people are infected and identifying them quickly and reliably can be a challenge. For infectious diseases which cause a fever, taking people’s temperatures when they exit or enter a country is one technique. This approach has been used in the past for the H1N1 influenza pandemic, Ebola, and SARS (another coronavirus).
However, a 2019 systematic review found that the existing evidence on entry and exit screening for infectious disease outbreaks suggested that the measures detected either no or very few cases for diseases such as SARS. The few studies that reported costs for screening for SARS and pandemic flu suggested that these measures were expensive to implement and consideration should be given to whether the money would be better spent on other measures.
However, the review noted that there may be other benefits from screening. For example, the measures may discourage ill people from travelling, raise awareness and educate the traveling public, and also allow flights from/to the affected areas to continue operating.
The review suggested that exit screening might be a higher priority than entry screening, and noted it has more commonly been recommended by the WHO in past outbreaks.

		What do trusted sources say?
The European Centre for Disease Prevention and Control (ECDC) has stated that “There is evidence that checking people at the airport (known as entry screening) is not very effective in preventing the spread of the virus, especially when people do not have symptoms. It is generally considered more useful to provide those arriving at airports with clear information explaining what to do if they develop symptoms after arrival.”	
The WHO similarly state that using temperature measurement alone for entry screening may not be very effective. They recommend that if it is implemented, governments should also take other measures such as collecting other relevant information from travellers and having systems in place to rapidly act on the data collected.